# Generated by Django 3.0.8 on 2020-07-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_data_train', models.TextField()),
                ('label_data_train', models.BooleanField()),
                ('referensi_data_train', models.TextField()),
            ],
        ),
    ]
