# Generated by Django 3.0.8 on 2020-07-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataTrain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatrain',
            old_name='label_data_train',
            new_name='label',
        ),
    ]
